build: Enable automatic builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,11 +21,44 @@ jobs:
       contents: read
     steps:
       - 
+        name: Run graphql query to get tag
+        uses: octokit/graphql-action@v3.x
+        id: latest_tag
+        with:
+          variables: |
+            repo: ${{ github.event.repository.name }}
+            owner: getumbrel
+          query: |
+            query tag($owner: String!, $repo: String!) {
+              repository(owner: $owner, name: $repo) {
+                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
+                  edges {
+                    node {
+                      name
+               } } } } }
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - 
+        name: Parse tag from query output
+        run: |
+          #!/bin/bash
+          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
+          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" == "null" ]] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
+          echo "Found tag: \"${latest_tag}\"" 
+          latest_version="${latest_tag%-*}"
+          major="${latest_version%%.*}"
+          minor="${latest_version#*.}"
+          minor="${minor%%.*}"
+          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+          echo "latest_minor=$major.$minor" >> $GITHUB_ENV
+      - 
         name: Check if the tag exists locally
         uses: action-pack/tag-exists@v1
         id: checkTag
         with: 
-          tag: 'v${{ vars.VERSION }}'         
+          tag: 'v${{ env.latest_tag }}'
       -
         name: Finish when found
         run: |
@@ -34,10 +67,10 @@ jobs:
           
           val="${{ steps.checkTag.outputs.exists }}"
 
-          [[ "${{ vars.VERSION }}" == *"rc"* ]] && beta="true"
-          [[ "${{ vars.VERSION }}" == *"beta"* ]] && beta="true"
-          [[ "${{ vars.VERSION }}" == *"test"* ]] && val="true"
-          [[ "${{ vars.VERSION }}" == *"alpha"* ]] && val="true"
+          [[ "${{ env.latest_tag }}" == *"rc"* ]] && beta="true"
+          [[ "${{ env.latest_tag }}" == *"beta"* ]] && beta="true"
+          [[ "${{ env.latest_tag }}" == *"test"* ]] && val="true"
+          [[ "${{ env.latest_tag }}" == *"alpha"* ]] && val="true"
 
           echo "beta=${beta}" >> $GITHUB_ENV
           echo "exists=${val}" >> $GITHUB_ENV
@@ -58,8 +91,9 @@ jobs:
             ${{ secrets.DOCKERHUB_REPO }}
             ghcr.io/${{ github.repository }}
           tags: |
+            type=raw,value=${{ env.latest_minor }},enable=${{ env.beta == 'false' }}
             type=raw,value=latest,priority=100,enable=${{ env.beta == 'false' }}
-            type=raw,value=${{ vars.VERSION }}
+            type=raw,value=${{ env.latest_tag }},priority=250
           labels: |
             org.opencontainers.image.title=${{ vars.NAME }}
         env:
